survos_meili:
    host: '%env(MEILI_SERVER)%'
    apiKey: '%env(MEILI_API_KEY)%'
    searchKey: '%env(MEILI_SEARCH_KEY)%'
    file_proxy:
        roots:
            test_sample: '%kernel.project_dir%/../kid-pan/test_sample'
            epstein: '/home/tac/Downloads/epstein'
    tools:
        - label: riccox
          url:  http://localhost:24900/
    embedders:
        small: # for testing, as cheap as possible
            source: 'openAi'
            model: 'text-embedding-3-small' # 2 cents/million tokens
            apiKey: '%env(OPENAI_API_KEY)%'
            template: 'templates/liquid/song.liquid'
        small_lyrics: # for testing, as cheap as possible
            source: 'openAi'
            model: 'text-embedding-3-small' # 2 cents/million tokens
            apiKey: '%env(OPENAI_API_KEY)%'
            template: 'templates/liquid/lyrics.liquid'

        best: # for production if budget allows
            source: 'openAi'
            model: 'text-embedding-3-large' # 13 cents/million tokens
            apiKey: '%env(OPENAI_API_KEY)%'
            template: 'templates/liquid/song.liquid'
        best_lyrics: # for production if budget allows
            source: 'openAi'
            model: 'text-embedding-3-large' # 13 cents/million tokens
            apiKey: '%env(OPENAI_API_KEY)%'
            template: 'templates/liquid/lyrics.liquid'
