survos_command:
#  resource: '@SurvosCommandBundle/config/routes.yaml'
  prefix: '/commands'
  type: attribute
  resource:
        path: '@SurvosCommandBundle/src/Controller/'
        namespace: Survos\CommandBundle\Controller
